connections.md, connectors/netsuite.md, developing-connectors/sdk/action.md, developing-connectors/sdk/methods.md, recipes/data-pills-and-mapping.md
https://github.com/workato/issues/issues/4235
=> fix broken links in SDK pages

recipes/data-pills-and-mapping.md
fixes https://github.com/workato/issues/issues/4359
=> fix link to string formulae

developing-connectors/sdk/object-definition.md
=> Added Label and sticky properties in Object definitions

book.json
=> Update default title to "Workato Docs"

developing-connectors/sdk/data-format/xml-format.md
=> 4549 improve xml docs

connectors/freshdesk.md
This page is linked from FD marketplace
=> Updated freshdesk docs page

developing-connectors/sdk/config-fields.md
=> Adding screenshot to config schema docs

on-prem.md
=> agent reinstall docs

_layouts/website/page.html
Fixes google analytics tracking
=> Fix google an analytics code

on-prem.md
=> Upgrade script

_layouts/website/page.html
=> Added VWO code for all Docs pages

_layouts/website/page.html, assets/scripts/main.js, styles/website.css
Closes https://github.com/workato/docs/issues/58
Closes https://github.com/workato/docs/issues/343
=> Correct scroll

_layouts/website/page.html, styles/website.css
Closes https://github.com/workato/docs/issues/265
Closes https://github.com/workato/docs/issues/222
=> Changed Return button and updated styles of header

SUMMARY.md, developing-connectors/sdk/dependent-pick-list.md, developing-connectors/sdk/pick-list.md
=> Adding 'Dependent pick list' topic to pick list section

developing-connectors/sdk/object-definition.md
added subdomain in control_type section.
=> added subdomain in control_type section.

on-prem.md
For this to work, the other pull request needs to be approved first: https://github.com/workato/docs/pull/332
=> Edit OPA installation guide & screenshots

connectors/salesforce.md
=> Salesforce real time setup

connectors/mysql.md, connectors/servicenow.md
=> Adjust table widths

SUMMARY.md, connectors/slack.md, workbot/workbot-actions.md, workbot/workbot-triggers.md, workbot/workbot-troubleshooting.md, workbot/workbot.md
- Updated table for workbot/workbot.md to html
- Updated title to include 'for Slack' for workbot/workbot-troubleshooting.md to html
- Updated all tables for /workbot/workbot-triggers.md to html
- Updated table for /workbot/workbot-actions.md to html
- Updated tables for connectors/slack.md to html
=> Update workbot tables to html

connectors/workday.md, connectors/workday/connection_setup.md
=> Workday update

on-prem.md
url property is strictly mandatory for JDBC
=> JDBC config fix

on-prem.md
=> LDAP configuration

connectors/mssql.md, connectors/mysql.md, connectors/oracle.md, connectors/postgresql.md, connectors/redshift.md
=> DB operators

recipes/steps.md
=> Typos in recipes/step.md

product-updates.md
Added enhancements from the issues that were closed.
=> New connector enhancements

developing-connectors/sdk/request.md
=> SDK verbs: options()

product-updates.md
@huilinn I couldn't find much from the list of closed GH issues, do add more if you know of other new features
=> 5th July updates

connectors/mssql.md, connectors/mysql.md, connectors/oracle.md, connectors/postgresql.md, connectors/redshift.md
=> Database: Unique key + Sort column constraints

product-updates.md
Could you add any connector enhancements that closed this past 2 weeks, I have only seen bug fixes or things that are only on preview @huilinn
=> Product updates 6-18Jul

workbot/workbot-commands.md
Very minor link fix.
Weird that Github didn't convert this from .md to .html.
=> Updated URL

developing-connectors/sdk/examples.md
=> Example SDKs links broke due to change in repo

SUMMARY.md
2 options currently showing as .md files. Fixes #553.
=> Adding sdk data format to summary

product-updates.md
=> Prod updates aug 6

connectors/oracle/select.md, connectors/postgresql/select.md
=> add docs for sql select

product-updates.md
Updates up till aug16. 
@eeshansim could you add to the point about PostgreSQL custom SQL?
=> Product updates 16 Aug

SUMMARY.md
@eeshansim can you help to merge this. We will launch the features soon.
=> Make public on-prem file docs before feature launch

developing-connectors/sdk.md
Fixed spelling and updated link to new custom adapter repository.
=> Update broken link and spelling

recipe-development-lifecycle.md
Moving the comments from #518 to a new branch because #542 was merged
=> Edits to import/export docs

product-updates.md
Some links yet to be added as docs not merged/posts not published.
=> Product updates 3 sept

connectors/mssql.md, connectors/mssql/new-row-trigger.md, connectors/mssql/select.md, connectors/mssql/stored-procedure.md, connectors/mssql/updated-row-trigger.md
=> SQL Server version restriction

SUMMARY.md
=> Link for connectors > http fix incorrect

connectors/mssql.md, connectors/mssql/new-row-trigger.md, connectors/mssql/updated-row-trigger.md, connectors/mysql/new-row-trigger.md, connectors/mysql/updated-row-trigger.md, connectors/oracle.md, connectors/oracle/new-row-trigger.md, connectors/oracle/updated-row-trigger.md, connectors/postgresql/new-row-trigger.md, connectors/postgresql/updated-row-trigger.md, connectors/redshift/new-row-trigger.md, connectors/redshift/updated-row-trigger.md
=> DB column constraints

connectors/oracle.md
=> Smart boolean conversion

recipes/group-data-mapping.md
=> Update group mapping doc

product-updates-log.md, product-updates.md
Duplicated product updates md file to save all update as a log (may be used in future implementation of a proper updates page)
=> Product updates (10 dec)

connectors/sap.md
=> SAP: change OPA folder

developing-connectors/http-v2.md
Sorry, here's the missing images for the auth section in https://docs.workato.com/developing-connectors/http-v2.html
=> Updated Missing Images

SUMMARY.md
Errors with content page (SUMMARY) on google text to speech
=> Edit Summary (google text to speech)

SUMMARY.md, developing-connectors/sdk/authentication/custom-authentication.md, developing-connectors/sdk/authentication/header-authentication.md
Added in example of Authorization bearer tokens based off user input field. I placed this in custom auth docs as an extension of how the apply block can be used.
=> Sdk custom auth enhancement

developing-connectors/sdk/secure_connection.md
previously showed the same image as before and after
=> Fixed image link

on-prem/profile.md
fixes workato/issues#8555
fixes #770
=> NTLM: username/password properties with example

connectors/sap.md
SAP: update library instruction
fix https://github.com/workato/sap_java/issues/72
=> SAP: update library instruction

workato-api.md, workato-api/recipe-lifecycle-management.md
=> New packages-api

developing-connectors/sdk/config-fields.md, developing-connectors/sdk/methods.md, formulas/number-formulas.md, formulas/string-formulas.md
added in methods from PR #21431
=> Updated ruby methods on the SDK

gulpfile.js, package-lock.json, package.json
Added `gulp` task which runs image optimizations using https://www.npmjs.com/package/gulp-imagemin
To run optimizations:
1. Install packages `npm install`
2. Run task `npm run imagemin` or  `gulp` (in this case `gulp` should be installed locally `npm install gulp -g`)
=> Added gulpfile for optimize images

recipes/jobs.md
=> corrected typo

recipe-ops.md, recipes/jobs.md, recipes/rerun-job.md
=> typo in running recipes

connectors/workday/connection_setup.md, connectors/workday/get_report.md, connectors/workday/scheduled_report.md, connectors/workday/workday_raas.md
=> typo in connectors workday

connections.md, features/if-conditions.md, recipes/version-management.md
=> Typo in Building Recipes, IF conditions

connectors/snowflake.md
=> Added instructions on the appropriate roles

api-mgmt/api-access-policies.md
Updated the Request Limit Policy 
For review: @alvinee @graceliching
=> Access Policy

user-accounts-and-teams/team-collaboration.md
fixes https://github.com/workato/issues/issues/9163
Changes:
- added JIT provisioning for custom roles
=> 9163 JIT provisioning for custom roles

connectors/concur.md
=> update concur terms

user-accounts-and-teams/team-collaboration.md
Adding in description of teams written by prod marketing
=> Add details to teams

SUMMARY.md, on-prem/logging.md, on-prem/run.md, on-prem/setup.md
=> OPA logging docs

developing-connectors/sdk/methods.md
Missing methods 
- [NA] Optimised every new image
- [NA] Added new files to SUMMARY.md
=> Arranged methods in alphabetical order and added missing ones.

assets/scripts/main.js, package-lock.json, package.json
Fixes https://github.com/workato/issues/issues/9483
=> Fix docs scrolling

api-mgmt/access-tokens.md
=> Correct type on api-mgmt/access-tokens.md

book.json, workato-api.md, workato-api/managed-users.md
=> Fixed the API doc

on-prem.md, on-prem/agents.md, on-prem/agents/connection.md, on-prem/agents/extension.md, on-prem/agents/logging.md, on-prem/agents/profile.md, on-prem/agents/run.md, on-prem/agents/setup.md, on-prem/groups.md, on-prem/groups/group-status.md
=> OPA: fix links

developing-connectors/sdk/action.md, developing-connectors/sdk/authentication/base_uri.md, developing-connectors/sdk/authentication/basic-authentication.md, developing-connectors/sdk/authentication/custom-authentication.md, developing-connectors/sdk/authentication/header-authentication.md, developing-connectors/sdk/authentication/oauth2-authentication.md, developing-connectors/sdk/authentication/test.md, developing-connectors/sdk/best-practices.md, developing-connectors/sdk/config-fields.md, developing-connectors/sdk/error-handling.md, developing-connectors/sdk/http-requests-and-response-handling.md, developing-connectors/sdk/methods.md, developing-connectors/sdk/object-definition.md, developing-connectors/sdk/pick-list.md, developing-connectors/sdk/quick-Start.md, developing-connectors/sdk/toggle-fields.md, developing-connectors/sdk/trigger/poll-trigger.md, developing-connectors/sdk/trigger/static-webhook-trigger.md, developing-connectors/sdk/trigger/webhook-trigger.md, developing-connectors/sdk/walk-through.md
=> make long pages readable

connectors/concur.md
=> remove unnecessary verb

developing-connectors/sdk/walk-through.md
missing connection argument in test block
Fixes #12345
=> Fix error in SDK example

connectors/sap.md
=> [FIX] SAP Note #

product-updates.md
=> Adding product updates for Sept

on-prem/agents/profile.md
Added comment to make config more transparent
=> SAP Partner Profile No.

connectors/workday/scheduled_report.md
=> update report trigger batch size

developing-connectors/sdk/methods.md, formulas/other-formulas.md
Formula update for enhancement workato/issues#9983
=> SHA1 update for formulas

recipe-development-lifecycle.md
=> Fix broken links

user-accounts-and-teams/team-collaboration.md
Fixes https://github.com/workato/issues/issues/10097
=> Update role privilege table

developing-connectors/cookbook/connector-building-defining-schema.md
=> Fix collapsible section

product-updates.md
Hi @eeliang can you help review and merge? Thanks!
=> Prod updates Oct

SUMMARY.md
=> Fix Amazon S3 summary link

security/ip-whitelists.md
DOcumentation update based on suggestion from Dimitris to add section on general traffic (like user browser) to Workato and how the IP addresses of those servers may be different from the traffic that's generated FROM Workato like on prem agent.
=> Add section for general traffic TO Workato and IP address difference

developing-connectors/sdk/methods.md
=> Added UUID to docs

features/activity-audit-log.md
- table of content
- remove reference to plan
=> Added table of content tag, removed reference to plan

connectors/sap.md
=> Updated info about Jco libraries

developing-connectors/sdk.md
=> Example link fix for `sdk.md` file

bin/deploy.sh, docs/.vuepress/config.js, package-lock.json, package.json
Closes https://github.com/workato/docs/issues/977
=> Add `sitemaps.xml` to improve Google indexing

docs/oem/jwt-direct-linking.md
Added pvt and pub keys generation from wiki to docs for visibility
=> Add keys generation

docs/user-accounts-and-teams/single-sign-on.md
Fix link to Microsoft Azure AD screenshot.
=> Fix link to screenshot

docs/oem/oem-api/connections.md, docs/oem/oem-api/oem-vendor-apis.md, docs/oem/oem-api/picklists.md
=> Changes to picklist API

docs/data-retention.md
Remove references to old plans and make it more generic for data retention policy.
=> Remove references to old plans

docs/data-retention.md
Remove plan table from the documentation.
=> Remove plan table

docs/developing-connectors/sdk/action.md, docs/developing-connectors/sdk/methods.md
=> added binary file download example

docs/.vuepress/config.js, docs/.vuepress/styles/index.styl, docs/oem/oem-api/adapters.md, docs/oem/oem-api/connections.md, docs/oem/oem-api/folders.md, docs/oem/oem-api/managed-users.md, docs/oem/oem-api/oem-vendor-apis.md, docs/oem/oem-api/picklists.md, docs/oem/oem-api/recipe-lifecycle-management.md, docs/oem/oem-api/recipes.md, docs/workato-api.md, docs/workato-api/jobs.md, docs/workato-api/recipe-lifecycle-management.md, docs/workato-api/recipes.md, package-lock.json, package.json
@th0r Hi Yuriy, can you help take a look at this PR and see why the table styles do not apply to some tables:
Eg. below where table width should be 100%: 
Thank you!
=> API table styles

docs/connectors/active_directory.md, docs/connectors/bigquery/new-row-trigger.md, docs/connectors/bigquery/select.md, docs/connectors/jdbc.md, docs/connectors/jira/actions.md, docs/connectors/mssql/introduction.md, docs/connectors/mysql.md, docs/connectors/on-prem-files/append-csv-line-action.md, docs/connectors/on-prem-files/download-file-action.md, docs/connectors/on-prem-files/list-files-action.md, docs/connectors/on-prem-files/move-file-action.md, docs/connectors/on-prem-files/rename-file-action.md, docs/connectors/on-prem-files/upload-file-action.md, docs/connectors/oracle/introduction.md, docs/connectors/postgresql.md, docs/connectors/wrike/create-folder-action.md, docs/connectors/wrike/update-folder-action.md, docs/developing-connectors/sdk/methods.md, docs/tools.md, docs/workbot/custom-workbot-vs-legacy-slash-commands.md
Issue example: https://docs.workato.com/connectors/bigquery.md#where-condition returns a 404
=> Fix broken href links in html elements

docs/connectors/snowflake/replicate.md
Addition to https://github.com/workato/docs/pull/1030
Include Workato Schema Mapper
- ~[ ] Added new files to `docs/vuepress/sidebar.js`~
```bash
npm run check
```
=> workato schema mapper

docs/recipes/recipe-security.md
=> Recipe security broken link

docs/formulas/other-formulas.md
Hint to address https://github.com/workato/issues/issues/11131
=> Add lookup table formula help

docs/.vuepress/sidebar.js, docs/connectors/google-drive/trigger-new-file-hierarchy.md
=> added docs for new gdrive trigger

docs/connectors/google-drive/trigger-new-file-hierarchy.md
=> Fixed hint

docs/on-prem/agents/profile.md
=> Update Applying a new configuration section

docs/security/ip-whitelists.md
Fixes #12345
```bash
npm run check
```
=> add sg{1,2}.workato.com IPs

docs/security/ip-whitelists.md
Fixes #12345
```bash
npm run check
```
=> IP whitelist table formatting fixes

docs/security/ip-whitelists.md
Fixes #12345
```bash
npm run check
```
=> add terminating |

README.md
Adds list of used `markdown-it` plugins to `README.md`
=> Mention `markdown-it-attrs` plugin in docs

docs/oem/oem-api/managed-users.md, docs/oem/oem-api/oem-vendor-apis.md
=> Multi origin configuration for embedding

docs/on-prem/agents/upgrade.md
Fixes workato/issues#11390
Some users run into an issue because we don't explicitly mention navigating to the agent directory
=> Clarify OPA upgrade step

docs/oem/admin-console/customers.md
=> Add iFrame origin URL

docs/.vuepress/styles/index.styl, docs/security/ip-whitelists.md
Fixes https://github.com/workato/issues/issues/11366
=> Add styles for `IP whitelists` table

docs/connectors/zendesk/update-record-action.md
removed linebreak which messed with the main header
=> Removed linebreak

docs/developing-connectors/sdk/methods.md
=> Fix docs for pull workato/workato#23528

docs/developing-connectors/sdk/methods.md, docs/developing-connectors/sdk/object-definition.md
Checkbox doesn't add a toggle field immediately
Fixes #12345
```bash
npm run check
```
=> SDK docs fix

docs/connectors/bigquery.md, docs/connectors/bigquery/get-query-result-action.md, docs/connectors/bigquery/insert.md, docs/connectors/bigquery/job-completed-trigger.md, docs/connectors/bigquery/new-row-trigger.md, docs/connectors/bigquery/scheduled-query-trigger.md, docs/connectors/bigquery/select.md
=> Bigquery enhancements docs

docs/.vuepress/sidebar.js, docs/on-prem/agents/versions.md, docs/security/ip-whitelists.md
Fixes https://github.com/workato/docs/issues/1112
```bash
npm run check
```
=> OPA version docs

docs/security/ip-whitelists.md
sg.workato.com's deprecation will be extended
=> Update OPA IPs

docs/recipes/cancel-job.md
=> Fixed couple of typos

docs/api-mgmt/jwt-workato-claim.md
Include line - Workato claim works most identity providers, including ADFS, Auth0, Okta and OneLogin
```bash
npm run check
```
=> Update JWT claim 

docs/developing-connectors/sdk/authentication/oauth2-authentication.md
fixes https://github.com/workato/issues/issues/11982
=> Updated docs for refresh block

docs/developing-connectors/sdk/trigger/webhook-trigger.md
There was some code for `type: paging_desc` so i removed that
=> Dynamic trigger code fix

docs/on-prem/agents/versions.md
=> OPA update 2.6.2

docs/.vuepress/sidebar.js, docs/api-mgmt/oauth2.md
=> APIM OAuth 2.0 minor changes

docs/connectors/sap.md
Make it explicit Program ID should be `Workato`
=> SAP: program id fix

docs/developing-connectors/sdk/object-definition.md
=> Object definitions 

docs/workbot/block-kit.md
Not applicable
```bash
npm run check
```
=> Block kit limitations
